name: final_canteen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  iconsax: ^0.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_cart: ^0.0.9
  jwt_decoder: ^2.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/brigadalogo.png
    - assets/sample/confirmorder.png
    - assets/sample/employee_dashboard.png
    - assets/sample/employee_managment_page.png
    - assets/sample/employee_menu_page.png
    - assets/sample/employee_order_page.png
    - assets/sample/finalregpage.png
    - assets/sample/landingpage.png
    - assets/sample/loginpage.png
    - assets/sample/regpage.png
    - assets/sample/staff_completedorder.png
    - assets/sample/staff_dashboard.png
    - assets/sample/staff_stockmngmnt.png
    - assets/sample/staff_userpayments.png
